apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: notification-system
data:
  DB_ENGINE: "django.db.backends.postgresql"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
  REDIS_URL: "redis://redis:6379/0"
  USER_SERVICE_URL: "http://user-service:8001"
  TEMPLATE_SERVICE_URL: "http://template-service:8002"
  EMAIL_SERVICE_URL: "http://email-service:8003"
  PUSH_SERVICE_URL: "http://push-service:8004"
  ADMIN_SERVICE_URL: "http://admin-service:8005"